### PR TITLE
Use `CGI.build_form` instead of manually creating the query string

### PR DESCRIPTION
**Pull request by asterite**
Hi @rhysd!

This is just because the code is very short and I'd like it to be shorter, and also to let you know that there's `CGI.build_form` (although it's not documented well yet).

I didn't test it because I don't know what's `ezoe` (and my Japanese is very bad, すみません), but it compiles :-)

### CODE REVIEW

**Comment by rhysd** [comment]
Hi @asterite!

Thank you very much for the contribution to such a joke repository ;)
I checked and ran the code and it seemed to work well.

**Comment by rhysd** [comment]
JFYI, Matz also seems to notice this repository :smile: 

https://twitter.com/yukihiro_matz/status/610842781091672064
https://twitter.com/matz_translated/status/610842797587976192

**Comment by asterite** [comment]
Wow! What does he say? Google translate is very bad for Japanese...

**Comment by rhysd** [comment]
He said "This may also work in Ruby without modification. Crystal is awesome!".  (although this doesn't work in Ruby because Crystal employs `&.` instead of `&` actually)

**Comment by asterite** [comment]
By the way, even if this is a "joke" repo, I like it because with very little code you can do something that's more or less useful. I also can't find type annotations in your code... most code requires them, but some doesn't, and it's very nice when that happens :-)

I found more things that you can simplify: instead of defining `error` you can use the standard library's [abort](https://github.com/manastech/crystal/blob/master/src/kernel.cr#L108) (it's also in [Ruby](http://ruby-doc.org/core-2.2.2/Kernel.html#method-i-abort)). And instead of `HTTP::Headers.new.add("Referer", "http://ask.fm/#{user}")` you can also do `HTTP::Headers{"Referer": "http://ask.fm/#{user}"}` which is a bit shorter (check the "Array-like types" section [here](http://crystal-lang.org/docs/syntax_and_semantics/literals/array.html)). 

Matz is such a nice guy. I really like him. One would think that he could maybe be offended because someone copied (to some point) his ideas and language, but he actually looks pretty pleased. Maybe it's because he also created his language by taking the best of some other languages (Perl, Smalltalk, Python). And because he inspires others :-)

Thank you for the translation! I like when they say "すげー" in Anime, sounds nice. I didn't think it was that word, I don't know why there's a small "tsu" (っ) there.

**Comment by asterite** [comment]
Um, I meant the "Hash-like types" section [here](http://crystal-lang.org/docs/syntax_and_semantics/literals/hash.html) (it's similar)

**Comment by rhysd** [comment]
Thanks a lot! I don't know many things yet about Crystal... I'll do some refactorings tonight.
- [x] Add type annotations to toplevel methods
- [x] Use `abort`
- [x] Use hash-like types

> Matz is such a nice guy.

Yes, he is very open-hearted.  He seems to think that copying ideas is a good thing in OSS. (I also think so.)

> I don't know why there's a small "tsu" (っ) there.

"っ" at the end of sentence sometime means similar to "!".  It just represents something like "excited".

**Comment by asterite** [comment]
Thanks for the explanation. I knew about "ne" and "yo", but not "tsu" at the end.

I actually prefer code without type annotations, but if you prefer them you can add them, of course :-)

**Comment by rhysd** [comment]
> Thanks for the explanation. I knew about "ne" and "yo", but not "tsu" at the end.

Japanese has many such things which are often called shujoshi (終助詞).
In addition, each dialects have many specific shujoshi.

> I actually prefer code without type annotations, but if you prefer them you can add them, of course :-)

I also like omitting type annotations, but readers of the code will be happy when type annotations exist.

**Pull request merged**
